batchsize: 1
batchsize_test: 10
iteration: 1000000
iteration_decay_start: 800000
seed: 0
display_interval: 100
progressbar_interval: 100
snapshot_interval: 50000
evaluation_interval: 5000

models:
  generator:
    fn: gen_models/generator.py
    name: Generator
    args:
      in_ch: 3
      out_ch: 4
      normalization: True

  discriminator:
      fn: dis_models/discriminator.py
      name: ConcatDiscriminator
      args:
        in_ch: 3
        out_ch: 4

dataset:
  fn: data.py
  name: train_test_dataset
  args:
    train_class_name: RGB2RGBCLOUD
    args_train:
      dir_rgb: # set your configuration
      dir_cloud: # set your configuration
      imlist_rgb: # set your configuration
      size: 256
      augmentation: False
    test_class_name: TestRGB
    args_test:
      dir_rgb: # set your configuration
      imlist_rgb: # set your configuration

adam:
  alpha: 0.0002
  beta1: 0.5
  beta2: 0.999

updater:
  fn: updater.py
  name: Updater
  args:
    n_dis: 1
    loss_type: dcgan
    weight_l1: 100

evaluation:
  fn: evaluation.py
  name: out_image
